### ISSUE TITLE
Users can reset their password

### ISSUE THREAD

**Issue by AltanStalker** [pthakkar3/PikUp#26]
## Acceptance Scenarios
- Given: The user has already registered prior to this and is on the login screen;
- When: The user presses the forgot password button;
               The user enters their verification email address in the appropriate field;
               The user presses the send password recovery button;
- Then: The user is redirected to the welcome page and receives an email with instructions describing how to reset their password.

## Done Criteria
User can reset their password, and it's updated on Firebase.

**Comment by TheArmando** [comment]
- Added a new button on the login screen that goes to a new reset password activity. Firebase handles it from there.
