### ISSUE TITLE
Users are notified upon entry of an incorrect username or password

### ISSUE THREAD

**Issue by AltanStalker** [pthakkar3/PikUp#27]
## Story/Task Details
- The user enters an invalid username or password.

## Acceptance Scenarios
- Given: The user has already registered prior to this and is on the login screen;
- When: The user presses the login button;
- Then: The user receives a notification that the username or password provided was invalid and the user remains on the login screen.

## Done Criteria
- A notification the username and password was incorrect. 
- Reasonably large and has a duration that is long enough so that the user knows whats going on.

**Comment by TheArmando** [comment]
Was already implemented.
