### ISSUE TITLE
Users can filter games by intensity level

### ISSUE THREAD

**Issue by AltanStalker** [pthakkar3/PikUp#5]
## Story/Task Details
- [ ] Task1

## Acceptance Scenarios
GIVEN: The user wants to apply an intensity filter;
WHEN: The user presses on the filter button;
The user selects the intensity level they want;
The user presses the apply filter button;
THEN: The user is presented with an updated list of games that match their selected intensity.

## Done Criteria
Feature works as defined above.

**Comment by TheArmando** [comment]
All filters have been added to the join screen and work as expected.
