### ISSUE TITLE
Users can filter games by sport

### ISSUE THREAD

**Issue by AltanStalker** [pthakkar3/PikUp#6]
## Story/Task Details
- [ ] Task1

## Acceptance Scenarios
SCENARIO: The user selects a set of sports they would like to play.
GIVEN: The user wants to apply a sport filter;
WHEN: The user presses on the filter button;
The user selects the sports they would like to play;
The user presses the apply filter button;
THEN: The user is presented with an updated list of games that match their selected games.

## Done Criteria
Feature works as defined above.

**Comment by TheArmando** [comment]
Users can use the sport spinner to select a sport that they wish to play and the list view in the sportsList is automatically updated with only sports that correspond to the selected sport.
