### ISSUE TITLE
User can filter games by who they want to play with

### ISSUE THREAD

**Issue by AltanStalker** [pthakkar3/PikUp#7]
## Story/Task Details
- [ ] Task1

## Acceptance Scenarios
SCENARIO: The user selects whether they want to play with students or faculty.
GIVEN: The user wants to apply a student/faculty filter;
WHEN: The user presses on the filter button;
The user selects either student or faculty;
The user presses the apply filter button;
THEN: The user is presented with an updated list of games that only have students or faculty

## Done Criteria
Feature works as defined above.

**Comment by TheArmando** [comment]
All filters have been added to the join screen and work as expected.
