### ISSUE TITLE
Users can filter games by location

### ISSUE THREAD

**Issue by AltanStalker** [pthakkar3/PikUp#8]
## Story/Task Details
- [ ] Task1

## Acceptance Scenarios
SCENARIO: The user selects what location they want to play at.
GIVEN: The user wants to apply a location filter;
WHEN: The user presses on the filter button;
The user selects from a list of common locations on campus;
The user presses apply filter button;
THEN: The user is presented with an updated list of games that are only being played at
locations the user selected.

## Done Criteria
Feature works as defined above.

**Comment by TheArmando** [comment]
All filters have been added to the join screen and work as expected.
